---
scenario:
  name: amazonlinux
platforms:
  - name: amazonlinux
    groups:
      - consul_instances
    image: dokken/amazonlinux
    dockerfile: ../_shared/Dockerfile.j2
    capabilities:
      - SYS_ADMIN
  - name: amazonlinux-2
    groups:
      - consul_instances
    image: dokken/amazonlinux-2
    dockerfile: ../_shared/Dockerfile.j2
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro